name: Release Docker Image

on:
  push:
    tags:
      - v*
        
env:
  AWS_REGION: "ca-central-1"

jobs:
  meta:
      name: Determine build state
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        # Get git version set up
        - name: Fetch all history for all tags and branches
          run: |
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git fetch --prune --unshallow
            
        - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v0
          with:
            versionSpec: '5.x'
            
        - name: Determine Version
          uses: gittools/actions/gitversion/execute@v0
          id: gitversion
          with:
            useConfigFile: true
      outputs:
        semVer: ${{ steps.gitversion.outputs.semVer }}
  build:
    runs-on: ubuntu-latest
    needs: meta
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
    
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Build and Release Docker images to Dockerhub
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: ./FirehoseHttp/Dockerfile
        push: true
        tags: |
          witchpixels/firehose-http:${{ needs.meta.outputs.semVer }}
          witchpixels/firehose-http:latest
          public.ecr.aws/k0p9f4k3/firehose-http:${{ needs.meta.outputs.semVer }}
          public.ecr.aws/k0p9f4k3/firehose-http:latest
    
